### ISSUE TITLE
Hexo3: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by sirtimbly** [visioncan/hexo-tag-flickr#7]
`hexo generate` is failing for me now, and I've isolated it down to this plugin. I can create a clean Hexo v3 install and generate successfully until after I install hexo-tag-flickr. 

```
C02KT0JBFFT3:hexo3-test2 tbendt$ npm install hexo-tag-flickr --save
hexo-tag-flickr@0.3.2 node_modules/hexo-tag-flickr
├── bluebird@2.10.2
└── hexo-util@0.1.7 (ent@2.2.0, highlight.js@8.9.1)
C02KT0JBFFT3:hexo3-test2 tbendt$ hexo generate
INFO  Start processing
ERROR Process failed: layout/archive.ejs
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: layout/category.ejs
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/tbendt/Sites/hexo3-test2/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/tbendt/Sites/hexo3-test2/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

And so on, for each .ejs file in _partial/post/

```
hexo -v
hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 15.4.0 darwin x64
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
```

**Comment by visioncan** [comment]
In hexo 3.2.0 plugins has changed, the release docs:

> If you set plugins list in _config.yml. Hexo will not detect plugin list automatically.


remove plugins section in your `_config.yml` should work fine!
